name: m3u8-dl
version: git
summary: m3u8-dl is a parallel HLS downloader.
description: Download HLS with as many concurrent downloads as you wish.
confinement: devmode
base: core18
parts:
  m3u8-dl:
    plugin: go
    go-importpath: github.com/nektro/m3u8-dl
    source: .
    source-type: git
    build-packages:
      - gcc
apps:
  m3u8-dl:
    command: bin/m3u8-dl
